TASagentTwitchBot.Core.WebServer/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

using TASagentTwitchBot.Core.WebServer.Models;

namespace TASagentTwitchBot.Core.WebServer.Controllers;

[Authorize(Roles = "Admin")]
public class UserRolesController : Controller
{
    private readonly UserManager<ApplicationUser> userManager;
    private readonly RoleManager<IdentityRole> roleManager;
    public UserRolesController(
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        this.roleManager = roleManager;
        this.userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        List<ApplicationUser> users = await userManager.Users.ToListAsync();
        List<UserRolesViewModel> userRolesViewModel = new List<UserRolesViewModel>();

        foreach (ApplicationUser user in users)
        {
            userRolesViewModel.Add(new UserRolesViewModel()
            {
                UserId = user.Id,
                Email = user.Email!,
                TwitchBroadcasterId = user.TwitchBroadcasterId,
                TwitchBroadcasterName = user.TwitchBroadcasterName,
                MonthlyTTSCharacterLimit = user.MonthlyTTSLimit,
                MonthlyTTSCharactersUsed = user.MonthlyTTSUsage,
                Roles = await GetUserRoles(user)
            });
        }

        return View(userRolesViewModel);
    }

    private async Task<List<string>> GetUserRoles(ApplicationUser user)
    {
        return new List<string>(await userManager.GetRolesAsync(user));
    }

    [Authorize(Roles = "SuperAdmin")]
    public async Task<IActionResult> Manage(string userId)
    {
        ViewBag.userId = userId;
        ApplicationUser? user = await userManager.FindByIdAsync(userId);

        if (user is null)
        {
            ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
            return View("NotFound");
        }

        ViewBag.UserName = user.UserName;
        List<ManageUserRolesViewModel> model = new List<ManageUserRolesViewModel>();
        foreach (IdentityRole role in roleManager.Roles)
        {
            ManageUserRolesViewModel userRolesViewModel = new ManageUserRolesViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name!
            };

            if (await userManager.IsInRoleAsync(user, role.Name!))
            {
                userRolesViewModel.Selected = true;
            }
            else
            {
                userRolesViewModel.Selected = false;
            }

            model.Add(userRolesViewModel);
        }

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = "SuperAdmin")]
    public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
    {
        ApplicationUser? user = await userManager.FindByIdAsync(userId);

        if (user is null)
        {
            return View();
        }

        IList<string> roles = await userManager.GetRolesAsync(user);
        IdentityResult result = await userManager.RemoveFromRolesAsync(user, roles);

        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Cannot remove user existing roles");
            return View(model);
        }

        result = await userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Cannot add selected roles to user");
            return View(model);
        }

        return RedirectToAction("Index");
    }


    [Authorize(Roles = "SuperAdmin")]
    public async Task<IActionResult> ManageTTS(string userId)
    {
        ViewBag.userId = userId;
        ApplicationUser? user = await userManager.FindByIdAsync(userId);

        if (user is null)
        {
            ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
            return View("NotFound");
        }

        ViewBag.UserName = user.UserName;
        ManageUserTTSViewModel model = new ManageUserTTSViewModel
        {
            MonthlyTTSCharacterLimit = user.MonthlyTTSLimit,
            MonthlyTTSCharactersUsed = user.MonthlyTTSUsage
        };

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = "SuperAdmin")]
    public async Task<IActionResult> ManageTTS(ManageUserTTSViewModel model, string userId)
    {
        ApplicationUser? user = await userManager.FindByIdAsync(userId);

        if (user is null)
        {
            return View();
        }

        if (user.MonthlyTTSUsage != model.MonthlyTTSCharactersUsed || user.MonthlyTTSLimit != model.MonthlyTTSCharacterLimit)
        {
            user.MonthlyTTSUsage = model.MonthlyTTSCharactersUsed;
            user.MonthlyTTSLimit = model.MonthlyTTSCharacterLimit;

            IdentityResult result = await userManager.UpdateAsync(user);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot update user TTS Usage");
                return View(model);
            }
        }

        return RedirectToAction("Index");
    }
}

TASagentTwitchBot.Core.WebServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - TASagentStreamBot WebServer</title>
  <link rel="stylesheet" href="~/Assets/libs/bootstrap/5/cyborg/bootstrap.min.css" />
  <link rel="stylesheet" href="~/Assets/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TASagentStreamBot WebServer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <!--
            <li class="nav-item">
              <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
              -->
            @if (User.IsInRole("Admin"))
            {
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserRoles" asp-action="Index">UserRoles</a>
              </li>
            }


          </ul>
          <partial name="_LoginPartial" />
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2021 - TASagentStreamBot WebServer<!-- - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>-->
    </div>
  </footer>
  <script src="~/Assets/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="~/Assets/libs/bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>
  <script src="~/Assets/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>